# Generated by Django 4.2.13 on 2024-05-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题2', max_length=30, verbose_name='标题1')),
                ('content', models.TextField(help_text='文本2', verbose_name='文本1')),
                ('b_date', models.DateField(help_text='时间2', verbose_name='时间')),
                ('read', models.IntegerField(help_text='阅读量2', verbose_name='阅读量1')),
                ('comment', models.IntegerField(help_text='评论数2', verbose_name='评论数1')),
            ],
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='类型2', max_length=20, verbose_name='类型1')),
                ('news', models.ManyToManyField(help_text='多对多2', to='news.newsinfo', verbose_name='多对多1')),
            ],
        ),
    ]
