# Generated by Django 4.2.13 on 2024-05-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsinfo',
            options={'verbose_name': '新闻信息表'},
        ),
        migrations.AlterModelOptions(
            name='newstype',
            options={'verbose_name': '新闻类型表'},
        ),
        migrations.AlterModelTable(
            name='newsinfo',
            table='news',
        ),
        migrations.AlterModelTable(
            name='newstype',
            table='type',
        ),
    ]
